apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog-wccu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mramdani-tenant/partner-catalog-1/partner-catalog-wccu@sha256:a9835c35b2a771b721629902726387c4719a5a82930bfd19b0dd30e8c2651ff9
        name: my-java-springboot
        resources: {}
status: {}
